export const openings: { [key: string]: string } = {
  // First moves
  'e4': 'King\'s Pawn Game',
  'd4': 'Queen\'s Pawn Game',
  'c4': 'English Opening',
  'Nf3': 'Reti Opening',
  'b3': 'Nimzo-Larsen Attack',
  'g3': 'King\'s Indian Attack',
  'f4': 'Bird\'s Opening',
  'b4': 'Polish Opening',
  'e3': 'Van\'t Kruijs Opening',
  'a3': 'Anderssen\'s Opening',
  'h3': 'Clemenz Opening',
  'a4': 'Ware Opening',
  'h4': 'Desprez Opening',
  'Nh3': 'Amar Opening',
  'Na3': 'Sodium Attack',
  'g4': 'Grob\'s Attack',
  'f3': 'Barnes Opening',
  'c3': 'Saragossa Opening',
  'd3': 'Mieses Opening',
  'e6': 'French Defense',
  'c5': 'Sicilian Defense',
  'd5': 'Queen\'s Pawn Game',
  'Nf6': 'Indian Defense',
  'e5': 'King\'s Pawn Game',
  'd6': 'Old Indian Defense',
  'g6': 'Modern Defense',
  
  // King's Pawn responses
  'e4 e5': 'Open Game',
  'e4 c5': 'Sicilian Defense',
  'e4 e6': 'French Defense',
  'e4 d6': 'Pirc Defense',
  'e4 d5': 'Scandinavian Defense',
  'e4 g6': 'Modern Defense',
  'e4 Nf6': 'Alekhine\'s Defense',
  'e4 b6': 'Owen\'s Defense',
  'e4 Nc6': 'Nimzowitsch Defense',
  'e4 f5': 'Latvian Gambit',
  'e4 c6': 'Caro-Kann Defense',
  'e4 b5': 'St. George Defense',
  'e4 a6': 'St. George Defense',
  'e4 f6': 'Barnes Defense',
  'e4 Nh6': 'Lemming Defense',
  
  // Queen's Pawn responses
  'd4 d5': 'Queen\'s Gambit',
  'd4 Nf6': 'Indian Defense',
  'd4 d6': 'Old Indian Defense',
  'd4 g6': 'King\'s Indian Defense',
  'd4 e6': 'Queen\'s Indian Defense',
  'd4 c5': 'Benoni Defense',
  'd4 f5': 'Dutch Defense',
  'd4 e5': 'Budapest Gambit',
  'd4 b6': 'Queen\'s Indian Defense',
  'd4 c6': 'Slav Defense',
  'd4 Nc6': 'Chigorin Defense',
  'd4 b5': 'Polish Defense',
  'd4 g5': 'Gibraltar Gambit',
  
  // Open Game continuations
  'e4 e5 Nf3': 'King\'s Knight Opening',
  'e4 e5 Bc4': 'Bishop\'s Opening',
  'e4 e5 d4': 'Center Game',
  'e4 e5 f4': 'King\'s Gambit',
  'e4 e5 Nc3': 'Vienna Game',
  'e4 e5 Bb5': 'Ruy Lopez',
  'e4 e5 d3': 'Philidor Defense',
  'e4 e5 c3': 'Alapin\'s Opening',
  'e4 e5 b3': 'Nimzowitsch-Larsen Attack',
  'e4 e5 g3': 'King\'s Indian Attack',
  
  // Ruy Lopez and variations
  'e4 e5 Nf3 Nc6 Bb5': 'Ruy Lopez',
  'e4 e5 Nf3 Nc6 Bb5 a6': 'Ruy Lopez, Morphy Defense',
  'e4 e5 Nf3 Nc6 Bb5 d6': 'Ruy Lopez, Steinitz Defense',
  'e4 e5 Nf3 Nc6 Bb5 Nf6': 'Ruy Lopez, Berlin Defense',
  'e4 e5 Nf3 Nc6 Bb5 f5': 'Ruy Lopez, Schliemann Defense',
  'e4 e5 Nf3 Nc6 Bb5 Bc5': 'Ruy Lopez, Classical Defense',
  'e4 e5 Nf3 Nc6 Bb5 d5': 'Ruy Lopez, Open Defense',
  'e4 e5 Nf3 Nc6 Bb5 a6 Ba4': 'Ruy Lopez, Morphy Defense',
  'e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6': 'Ruy Lopez, Morphy Defense',
  'e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O': 'Ruy Lopez, Morphy Defense',
  'e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O Be7': 'Ruy Lopez, Morphy Defense',
  'e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O Be7 Re1': 'Ruy Lopez, Morphy Defense',
  'e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O Be7 Re1 b5': 'Ruy Lopez, Morphy Defense',
  'e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O Be7 Re1 b5 Bb3': 'Ruy Lopez, Morphy Defense',
  
  // Italian Game and variations
  'e4 e5 Nf3 Nc6 Bc4': 'Italian Game',
  'e4 e5 Nf3 Nc6 Bc4 Bc5': 'Italian Game, Giuoco Piano',
  'e4 e5 Nf3 Nc6 Bc4 Bc5 b4': 'Italian Game, Evans Gambit',
  'e4 e5 Nf3 Nc6 Bc4 Nf6': 'Italian Game, Two Knights Defense',
  'e4 e5 Nf3 Nc6 Bc4 Bc5 c3': 'Italian Game, Giuoco Piano',
  'e4 e5 Nf3 Nc6 Bc4 Bc5 c3 Nf6': 'Italian Game, Giuoco Piano',
  'e4 e5 Nf3 Nc6 Bc4 Bc5 c3 Nf6 d4': 'Italian Game, Giuoco Piano',
  'e4 e5 Nf3 Nc6 Bc4 Bc5 c3 Nf6 d4 exd4': 'Italian Game, Giuoco Piano',
  'e4 e5 Nf3 Nc6 Bc4 Bc5 c3 Nf6 d4 exd4 cxd4': 'Italian Game, Giuoco Piano',
  'e4 e5 Nf3 Nc6 Bc4 Bc5 c3 Nf6 d4 exd4 cxd4 Bb4+': 'Italian Game, Giuoco Piano',
  
  // Scotch Game
  'e4 e5 Nf3 Nc6 d4': 'Scotch Game',
  'e4 e5 Nf3 Nc6 d4 exd4 Nxd4': 'Scotch Game, Classical Variation',
  'e4 e5 Nf3 Nc6 d4 exd4 Nxd4 Bc5': 'Scotch Game, Classical Variation',
  'e4 e5 Nf3 Nc6 d4 exd4 Nxd4 Bc5 Be3': 'Scotch Game, Classical Variation',
  'e4 e5 Nf3 Nc6 d4 exd4 Nxd4 Bc5 Be3 Qf6': 'Scotch Game, Classical Variation',
  'e4 e5 Nf3 Nc6 d4 exd4 Nxd4 Bc5 Be3 Qf6 c3': 'Scotch Game, Classical Variation',
  
  // Sicilian Defense variations
  'e4 c5 Nf3': 'Sicilian Defense',
  'e4 c5 Nf3 d6': 'Sicilian Defense, Classical Variation',
  'e4 c5 Nf3 e6': 'Sicilian Defense, Scheveningen Variation',
  'e4 c5 Nf3 Nc6': 'Sicilian Defense, Classical Variation',
  'e4 c5 Nf3 g6': 'Sicilian Defense, Dragon Variation',
  'e4 c5 Nf3 Nf6': 'Sicilian Defense, Alapin Variation',
  'e4 c5 c3': 'Sicilian Defense, Alapin Variation',
  'e4 c5 d4': 'Sicilian Defense, Grand Prix Attack',
  'e4 c5 b3': 'Sicilian Defense, Snyder Variation',
  
  // French Defense variations
  'e4 e6 d4': 'French Defense',
  'e4 e6 d4 d5': 'French Defense',
  'e4 e6 d4 d5 e5': 'French Defense, Advance Variation',
  'e4 e6 d4 d5 Nc3': 'French Defense, Classical Variation',
  'e4 e6 d4 d5 Nc3 Nf6': 'French Defense, Classical Variation',
  'e4 e6 d4 d5 Nc3 Bb4': 'French Defense, Winawer Variation',
  'e4 e6 d4 d5 Nc3 dxe4': 'French Defense, Rubinstein Variation',
  
  // Caro-Kann Defense variations
  'e4 c6 d4': 'Caro-Kann Defense',
  'e4 c6 d4 d5': 'Caro-Kann Defense',
  'e4 c6 d4 d5 e5': 'Caro-Kann Defense, Advance Variation',
  'e4 c6 d4 d5 Nc3': 'Caro-Kann Defense, Classical Variation',
  'e4 c6 d4 d5 Nc3 dxe4': 'Caro-Kann Defense, Classical Variation',
  'e4 c6 d4 d5 Nc3 Bb4': 'Caro-Kann Defense, Panov-Botvinnik Attack',
  
  // Queen's Gambit variations
  'd4 d5 c4': 'Queen\'s Gambit',
  'd4 d5 c4 e6': 'Queen\'s Gambit Declined',
  'd4 d5 c4 c6': 'Slav Defense',
  'd4 d5 c4 dxc4': 'Queen\'s Gambit Accepted',
  'd4 d5 c4 e6 Nc3': 'Queen\'s Gambit Declined',
  'd4 d5 c4 e6 Nc3 Nf6': 'Queen\'s Gambit Declined',
  'd4 d5 c4 e6 Nc3 Nf6 Bg5': 'Queen\'s Gambit Declined, Orthodox Defense',
  
  // King's Indian Defense variations
  'd4 Nf6 c4 g6': 'King\'s Indian Defense',
  'd4 Nf6 c4 g6 Nc3': 'King\'s Indian Defense',
  'd4 Nf6 c4 g6 Nc3 Bg7': 'King\'s Indian Defense',
  'd4 Nf6 c4 g6 Nc3 Bg7 e4': 'King\'s Indian Defense, Classical Variation',
  'd4 Nf6 c4 g6 Nc3 Bg7 e4 d6': 'King\'s Indian Defense, Classical Variation',
  'd4 Nf6 c4 g6 Nc3 Bg7 e4 d6 Nf3': 'King\'s Indian Defense, Classical Variation',
  
  // Other common openings
  'c4 e5': 'English Opening',
  'Nf3 d5': 'Reti Opening',
  'b3 e5': 'Nimzo-Larsen Attack',
  'g3 d5': 'King\'s Indian Attack',
  'f4 d5': 'Bird\'s Opening',
  'c4 c5': 'English Opening, Symmetrical Variation',
  'c4 Nf6': 'English Opening, Nimzowitsch Variation',
  'c4 e6': 'English Opening, Agincourt Defense',
  'c4 g6': 'English Opening, Keres Defense',
  'c4 b6': 'English Opening, Agincourt Defense',
  'c4 f5': 'English Opening, Anglo-Dutch Defense',
  'c4 d5': 'English Opening, Anglo-Scandinavian Defense',
  'c4 d6': 'English Opening, Agincourt Defense',
  'c4 Nc6': 'English Opening, Nimzowitsch Variation',
  'c4 b5': 'English Opening, Agincourt Defense',
  'c4 g5': 'English Opening, Agincourt Defense',
}; 